### ISSUE TITLE
Add unit test and code coverage badges to README

### ISSUE THREAD

**Issue by hjacobs** [commonsearch/cosr-back#32]
Rather easy to do and helps seeing the project "health" immediately:

* add build status badge (https://travis-ci.org/commonsearch/cosr-back)
* add code coverage badge (using a service such as coveralls or codecov)
* maybe add license badge too

IMHO a lot of people (including myself) look for these badges (e.g. to get a first impression on test quality).

Example project with (IMHO relevant) badges: https://github.com/zalando/connexion

**Comment by sylvinus** [comment]
Thanks @hjacobs for the suggestion!

I originally thought about it but felt it was somewhat annoying to have third-party images on the READMEs. However after looking deeper into it, it looks like GitHub actually [proxies](https://help.github.com/articles/why-do-my-images-have-strange-urls/) them, which makes it okay :)

Adding code coverage is also a great idea. I will give coveralls a try!

**Comment by sylvinus** [comment]
Coverage is working :) Thanks!
