### ISSUE TITLE
Advertising Lists

### ISSUE THREAD

**Issue by indolering** [commonsearch/cosr-back#59]
[FilterLists](https://filterlists.com/) is a meta-list for advertising, spam, astroturfing, fraud, and piracy.  It would be relatively easy to manually pull in many of these feeds, but some require parsing as the advertising filters often contain regular sites with CSS selectors.  I've emailed the admin and asked if s/he could produce a JSON or TXT master list that we can parse.

I've also submitted PrivacyBadger's yellowlist for inclusion as well.  If that isn't added for some reason, we should add it.

**Comment by indolering** [comment]
They are apparently working on version 2.0 of the site and are considering adding a machine-readable data file.  It might take some time, however.

**Comment by sylvinus** [comment]
FilterLists definitely looks great, and I'm glad to know they're working on machine-readable data files. Let's continue tracking this at #34.

**Comment by collinbarrett** [comment]
Hey, maintainer of [FilterLists](https://filterlists.com/) here. I just launched v2 of the site, and the data is now in json format on GitHub over [here](https://github.com/collinbarrett/FilterLists). Feel free to use.
